{
    "openapi": "3.0.0",
    "info": {
        "title": "Radhiyan Pet and Care",
        "version": "1.0.0"
    },
    "paths": {
        "/api/register": {
            "post": {
                "tags": [
                    "Register"
                ],
                "summary": "User Register",
                "description": "User Register here",
                "operationId": "Register",
                "requestBody": {
                    "content": {
                        "multipart/form-data": {
                            "schema": {
                                "required": [
                                    "name",
                                    "email",
                                    "password"
                                ],
                                "properties": {
                                    "name": {
                                        "type": "text"
                                    },
                                    "email": {
                                        "type": "text"
                                    },
                                    "password": {
                                        "type": "password"
                                    }
                                },
                                "type": "object"
                            }
                        },
                        "application/json": {
                            "schema": {},
                            "examples": {
                                "User Register": {
                                    "summary": "User Register",
                                    "value": {
                                        "name": "DW",
                                        "email": "testingvalue@gmail.com",
                                        "password": "111111"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Register Successfully",
                        "content": {
                            "application/json": {
                                "schema": {}
                            }
                        }
                    },
                    "200": {
                        "description": "Register Successfully",
                        "content": {
                            "application/json": {
                                "schema": {}
                            }
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "content": {
                            "application/json": {
                                "schema": {}
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request"
                    },
                    "404": {
                        "description": "Resource Not Found"
                    }
                }
            }
        },
        "/api/login": {
            "post": {
                "tags": [
                    "Login Username"
                ],
                "summary": "Login",
                "description": "Login RPC here",
                "operationId": "Login Username",
                "requestBody": {
                    "content": {
                        "multipart/form-data": {
                            "schema": {
                                "required": [
                                    "email",
                                    "password"
                                ],
                                "properties": {
                                    "email": {
                                        "type": "text"
                                    },
                                    "password": {
                                        "type": "password"
                                    }
                                },
                                "type": "object"
                            }
                        },
                        "application/json": {
                            "schema": {},
                            "examples": {
                                "Login User": {
                                    "summary": "Login User",
                                    "value": {
                                        "email": "yolo@gmail.com",
                                        "password": "111111"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Login Successfully",
                        "content": {
                            "application/json": {
                                "schema": {}
                            }
                        }
                    },
                    "200": {
                        "description": "Login Successfully",
                        "content": {
                            "application/json": {
                                "schema": {}
                            }
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "content": {
                            "application/json": {
                                "schema": {}
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request"
                    },
                    "404": {
                        "description": "Resource Not Found"
                    }
                }
            }
        },
        "/api/logout": {
            "post": {
                "tags": [
                    "Logout Username"
                ],
                "summary": "Logout",
                "description": "Logout RPC",
                "operationId": "Logout Username",
                "requestBody": {
                    "content": {
                        "multipart/form-data": {
                            "schema": {
                                "required": [
                                    "token"
                                ],
                                "properties": {
                                    "token": {
                                        "type": "text"
                                    }
                                },
                                "type": "object"
                            }
                        },
                        "application/json": {
                            "schema": {},
                            "examples": {
                                "Logout User": {
                                    "summary": "Logout User",
                                    "value": {
                                        "token": ""
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Login Successfully",
                        "content": {
                            "application/json": {
                                "schema": {}
                            }
                        }
                    },
                    "200": {
                        "description": "Login Successfully",
                        "content": {
                            "application/json": {
                                "schema": {}
                            }
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "content": {
                            "application/json": {
                                "schema": {}
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request"
                    },
                    "404": {
                        "description": "Resource Not Found"
                    }
                },
                "security": [
                    {
                        "apiAuth": []
                    }
                ]
            }
        },
        "/api/datastaticlocation": {
            "delete": {
                "tags": [
                    "Data Static"
                ],
                "summary": "Delete Data Static Location",
                "description": "Delete data static here , need id data static",
                "operationId": "datastaticlocation",
                "requestBody": {
                    "content": {
                        "multipart/form-data": {
                            "schema": {
                                "required": [
                                    "id"
                                ],
                                "properties": {
                                    "id": {
                                        "type": "integer"
                                    }
                                },
                                "type": "object"
                            }
                        },
                        "application/json": {
                            "schema": {},
                            "examples": {
                                "delete id 1": {
                                    "summary": "Delete data static",
                                    "value": {
                                        "id": 1
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Delete data static Successfully",
                        "content": {
                            "application/json": {
                                "schema": {}
                            }
                        }
                    },
                    "200": {
                        "description": "Delete data static Successfully",
                        "content": {
                            "application/json": {
                                "schema": {}
                            }
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "content": {
                            "application/json": {
                                "schema": {}
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request"
                    },
                    "404": {
                        "description": "Resource Not Found"
                    }
                },
                "security": [
                    {
                        "apiAuth": []
                    }
                ]
            }
        },
        "/api/datastatic": {
            "get": {
                "tags": [
                    "Data Static"
                ],
                "summary": "Get Data Static",
                "description": "Get Data Static",
                "operationId": "datastatic",
                "parameters": [
                    {
                        "name": "body",
                        "in": "path",
                        "required": true,
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "orderby": {
                                            "type": "text",
                                            "example": "asc"
                                        },
                                        "column": {
                                            "type": "text",
                                            "example": "value"
                                        },
                                        "keyword": {
                                            "type": "text",
                                            "example": "Messenger"
                                        },
                                        "page": {
                                            "type": "number",
                                            "example": "1"
                                        },
                                        "total_per_page": {
                                            "type": "number",
                                            "example": "14"
                                        }
                                    },
                                    "type": "object"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Get Data Static Successfully",
                        "content": {
                            "application/json": {
                                "schema": {}
                            }
                        }
                    },
                    "200": {
                        "description": "Get Data Static Successfully",
                        "content": {
                            "application/json": {
                                "schema": {}
                            }
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "content": {
                            "application/json": {
                                "schema": {}
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request"
                    },
                    "404": {
                        "description": "Resource Not Found"
                    }
                },
                "security": [
                    {
                        "apiAuth": []
                    }
                ]
            },
            "post": {
                "tags": [
                    "Location"
                ],
                "summary": "Insert Data Static",
                "description": "Insert Data Static",
                "operationId": "Insert Data Static",
                "requestBody": {
                    "content": {
                        "multipart/form-data": {
                            "schema": {
                                "required": [
                                    "keyword",
                                    "name"
                                ],
                                "properties": {
                                    "keyword": {
                                        "type": "text"
                                    },
                                    "name": {
                                        "type": "text"
                                    }
                                },
                                "type": "object"
                            }
                        },
                        "application/json": {
                            "schema": {},
                            "examples": {
                                "Insert Data Static": {
                                    "summary": "Insert Data static",
                                    "value": {
                                        "keyword": "Pemakaian",
                                        "name": "Sharing Account"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Register Successfully",
                        "content": {
                            "application/json": {
                                "schema": {}
                            }
                        }
                    },
                    "200": {
                        "description": "Register Successfully",
                        "content": {
                            "application/json": {
                                "schema": {}
                            }
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "content": {
                            "application/json": {
                                "schema": {}
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request"
                    },
                    "404": {
                        "description": "Resource Not Found"
                    }
                },
                "security": [
                    {
                        "apiAuth": []
                    }
                ]
            }
        },
        "/api/fasilitas": {
            "get": {
                "tags": [
                    "Fasilitas"
                ],
                "summary": "Get Fasilitas",
                "description": "get Fasilitas",
                "operationId": "fasilitas",
                "parameters": [
                    {
                        "name": "body",
                        "in": "path",
                        "required": true,
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "orderby": {
                                            "type": "text",
                                            "example": "asc"
                                        },
                                        "column": {
                                            "type": "text",
                                            "example": "fasilitasName"
                                        },
                                        "keyword": {
                                            "type": "text",
                                            "example": "RPC"
                                        },
                                        "page": {
                                            "type": "number",
                                            "example": "1"
                                        },
                                        "total_per_page": {
                                            "type": "number",
                                            "example": "5"
                                        }
                                    },
                                    "type": "object"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Get Data Location Successfully",
                        "content": {
                            "application/json": {
                                "schema": {}
                            }
                        }
                    },
                    "200": {
                        "description": "Get Data Location Successfully",
                        "content": {
                            "application/json": {
                                "schema": {}
                            }
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "content": {
                            "application/json": {
                                "schema": {}
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request"
                    },
                    "404": {
                        "description": "Resource Not Found"
                    }
                },
                "security": [
                    {
                        "apiAuth": []
                    }
                ]
            },
            "post": {
                "tags": [
                    "Fasilitas"
                ],
                "summary": "Insert Fasilitas",
                "description": "Insert Fasilitas",
                "operationId": "Insert Fasilitas",
                "requestBody": {
                    "content": {
                        "multipart/form-data": {
                            "schema": {
                                "required": [
                                    "fasilitasName",
                                    "locationName",
                                    "capacity",
                                    "status",
                                    "introduction",
                                    "description"
                                ],
                                "properties": {
                                    "fasilitasName": {
                                        "type": "text"
                                    },
                                    "locationName": {
                                        "type": "text"
                                    },
                                    "capacity": {
                                        "type": "integer"
                                    },
                                    "status": {
                                        "type": "integer"
                                    },
                                    "introduction": {
                                        "type": "text"
                                    },
                                    "description": {
                                        "type": "text"
                                    }
                                },
                                "type": "object"
                            }
                        },
                        "application/json": {
                            "schema": {},
                            "examples": {
                                "Insert Fasilitas": {
                                    "summary": "Insert Fasilitas",
                                    "value": {
                                        "fasilitasName": "Kandang Maxi",
                                        "locationName": "RPC Permata Hijau Pekanbaru",
                                        "capacity": 1,
                                        "status": 1,
                                        "introduction": "Kandang maxi Extra bed for you love pet",
                                        "description": "Ukuran 8M Cocok untuk tipe anjing besar, seperti golden retriever"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Register Fasilitas Successfully",
                        "content": {
                            "application/json": {
                                "schema": {}
                            }
                        }
                    },
                    "200": {
                        "description": "Register Fasilitas Successfully",
                        "content": {
                            "application/json": {
                                "schema": {}
                            }
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "content": {
                            "application/json": {
                                "schema": {}
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request"
                    },
                    "404": {
                        "description": "Resource Not Found"
                    }
                },
                "security": [
                    {
                        "apiAuth": []
                    }
                ]
            }
        },
        "/api/detailfasilitas": {
            "get": {
                "tags": [
                    "Fasilitas"
                ],
                "summary": "Get Fasilitas Detail",
                "description": "Get Fasilitas Detail",
                "operationId": "detailfasilitas",
                "parameters": [
                    {
                        "name": "body",
                        "in": "path",
                        "required": true,
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "id": {
                                            "type": "text",
                                            "example": "1"
                                        }
                                    },
                                    "type": "object"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Get Data Location Detail Successfully",
                        "content": {
                            "application/json": {
                                "schema": {}
                            }
                        }
                    },
                    "200": {
                        "description": "Get Data Location Detail Successfully",
                        "content": {
                            "application/json": {
                                "schema": {}
                            }
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "content": {
                            "application/json": {
                                "schema": {}
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request"
                    },
                    "404": {
                        "description": "Resource Not Found"
                    }
                },
                "security": [
                    {
                        "apiAuth": []
                    }
                ]
            }
        },
        "/api/contactlocation": {
            "delete": {
                "tags": [
                    "Location"
                ],
                "summary": "Delete Contact Location",
                "description": "Delete Contact Location , ex: email, messenger, operational(each represent column table, ex: email->location_email)",
                "operationId": "Delete Contact Location",
                "requestBody": {
                    "content": {
                        "multipart/form-data": {
                            "schema": {
                                "properties": {
                                    "keyword": {
                                        "type": "text"
                                    },
                                    "id": {
                                        "type": "integer"
                                    }
                                },
                                "type": "object"
                            }
                        },
                        "application/json": {
                            "schema": {},
                            "examples": {
                                "Delete Contact Location": {
                                    "summary": "Delete Contact Location",
                                    "value": {
                                        "keyword": "telepon",
                                        "id": 1
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Delete branch Successfully",
                        "content": {
                            "application/json": {
                                "schema": {}
                            }
                        }
                    },
                    "200": {
                        "description": "Delete branch Successfully",
                        "content": {
                            "application/json": {
                                "schema": {}
                            }
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "content": {
                            "application/json": {
                                "schema": {}
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request"
                    },
                    "404": {
                        "description": "Resource Not Found"
                    }
                },
                "security": [
                    {
                        "apiAuth": []
                    }
                ]
            }
        },
        "/api/location": {
            "get": {
                "tags": [
                    "Location"
                ],
                "summary": "Get Location",
                "description": "get Location",
                "operationId": "location",
                "parameters": [
                    {
                        "name": "body",
                        "in": "path",
                        "required": true,
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "orderby": {
                                            "type": "text",
                                            "example": "asc"
                                        },
                                        "column": {
                                            "type": "text",
                                            "example": "codeLocation, locationName, isBranch, status, introduction"
                                        },
                                        "keyword": {
                                            "type": "text",
                                            "example": "Jakarta"
                                        },
                                        "page": {
                                            "type": "number",
                                            "example": "1"
                                        },
                                        "total_per_page": {
                                            "type": "number",
                                            "example": "5"
                                        }
                                    },
                                    "type": "object"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Get Data Location Successfully",
                        "content": {
                            "application/json": {
                                "schema": {}
                            }
                        }
                    },
                    "200": {
                        "description": "Get Data Location Successfully",
                        "content": {
                            "application/json": {
                                "schema": {}
                            }
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "content": {
                            "application/json": {
                                "schema": {}
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request"
                    },
                    "404": {
                        "description": "Resource Not Found"
                    }
                },
                "security": [
                    {
                        "apiAuth": []
                    }
                ]
            },
            "put": {
                "tags": [
                    "Location"
                ],
                "summary": "Update Location",
                "description": "Update Location",
                "operationId": "Update Location",
                "requestBody": {
                    "content": {
                        "multipart/form-data": {
                            "schema": {
                                "required": [
                                    "locationName",
                                    "isBranch",
                                    "password"
                                ],
                                "properties": {
                                    "name": {
                                        "type": "text"
                                    }
                                },
                                "type": "object"
                            }
                        },
                        "application/json": {
                            "schema": {},
                            "examples": {
                                "update Location": {
                                    "summary": "update Location",
                                    "value": {
                                        "id": "1",
                                        "locationName": "RPC Permata Hijau Jakarta",
                                        "isBranch": "1",
                                        "status": "0",
                                        "introduction": "RPC Permata Hijau Jakarta, your satisfation is out top priority",
                                        "description": "Dibangun di tahun 2022, RPC Permata Hijau Jakarta sudah melayani berbagai lebih dari 100 ribu client diberbagai wilayah dijakarta, fasilitas yang lengkap dan terjamin security",
                                        "image": "D:\\\\ImageFolder\\\\ExamplePath\\\\ImageRPCPermataHijauJakarta.jpg",
                                        "imageTitle": "ImageRPCPermataHijauJakarta.jpg",
                                        "alamat_location": [
                                            {
                                                "codeLocation": "366f70e7",
                                                "alamatJalan": "Jalan U 27 B Palmerah Barat no 206 Jakarta Barat 11480",
                                                "infoTambahan": "Patokan Jalan : terminal busway jakarta selatan itc permata hijau",
                                                "kotaID": "Jakarta Selatan",
                                                "provinsiID": "Kebayoran Lama",
                                                "kodePos": 12210,
                                                "negara": "Indonesia",
                                                "parkir": "Yes",
                                                "pemakaian": "Apartement"
                                            }
                                        ],
                                        "operational_days": [
                                            {
                                                "days_name": "Monday",
                                                "from_time": "10:00PM",
                                                "to_time": "10:00PM",
                                                "all_day": 1
                                            },
                                            {
                                                "days_name": "Monday",
                                                "from_time": "10:00PM",
                                                "to_time": "10:00PM",
                                                "all_day": 1
                                            },
                                            {
                                                "days_name": "Tuesday",
                                                "from_time": "12:00PM",
                                                "to_time": "13:00PM",
                                                "all_day": 1
                                            },
                                            {
                                                "days_name": "Wednesday",
                                                "from_time": "10:00PM",
                                                "to_time": "10:00PM",
                                                "all_day": 1
                                            }
                                        ],
                                        "messenger": [
                                            {
                                                "pemakaian": "Utama",
                                                "namaMessenger": "(021) 3851185",
                                                "tipe": "Fax"
                                            },
                                            {
                                                "pemakaian": "Utama",
                                                "namaMessenger": "(021) 012345678",
                                                "tipe": "Office"
                                            }
                                        ],
                                        "email": [
                                            {
                                                "pemakaian": "Utama",
                                                "namaPengguna": "wahyudidanny23@gmail.com",
                                                "tipe": "Personal"
                                            },
                                            {
                                                "pemakaian": "Secondary",
                                                "namaPengguna": "wahyudidanny25@gmail.com",
                                                "tipe": "Personal"
                                            }
                                        ],
                                        "telepon": [
                                            {
                                                "pemakaian": "Utama",
                                                "nomorTelepon": "087888821648",
                                                "tipe": "Telepon Selular"
                                            },
                                            {
                                                "pemakaian": "Secondary",
                                                "nomorTelepon": "085265779499",
                                                "tipe": "Whatshapp"
                                            }
                                        ]
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Update Successfully",
                        "content": {
                            "application/json": {
                                "schema": {}
                            }
                        }
                    },
                    "200": {
                        "description": "Update Successfully",
                        "content": {
                            "application/json": {
                                "schema": {}
                            }
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "content": {
                            "application/json": {
                                "schema": {}
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request"
                    },
                    "404": {
                        "description": "Resource Not Found"
                    }
                },
                "security": [
                    {
                        "apiAuth": []
                    }
                ]
            },
            "post": {
                "tags": [
                    "Location"
                ],
                "summary": "Insert Location",
                "description": "Insert Location",
                "operationId": "Insert Location",
                "requestBody": {
                    "content": {
                        "multipart/form-data": {
                            "schema": {
                                "required": [
                                    "locationName",
                                    "isBranch",
                                    "password"
                                ],
                                "properties": {
                                    "name": {
                                        "type": "text"
                                    }
                                },
                                "type": "object"
                            }
                        },
                        "application/json": {
                            "schema": {},
                            "examples": {
                                "Insert Location": {
                                    "summary": "Insert Location",
                                    "value": {
                                        "locationName": "RPC Permata Hijau Pekanbaru",
                                        "isBranch": "0",
                                        "status": "1",
                                        "introduction": "RPC Permata Hijau Pekanbaru, the best pet shop in the pekanbaru",
                                        "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum fuga, alias placeat necessitatibus dolorem ea autem tempore omnis asperiores nostrum, excepturi a unde mollitia blanditiis iusto. Dolorum tempora enim atque.",
                                        "image": "D:\\\\ImageFolder\\\\ExamplePath\\\\ImageRPCPermataHijau.jpg",
                                        "imageTitle": "ImageRPCPermataHijau.jpg",
                                        "alamat_location": [
                                            {
                                                "alamatJalan": "Jalan U 27 B Palmerah Barat no 206 Jakarta Barat 11480",
                                                "infoTambahan": "Didepan nasi goreng kuning arema, disebelah bubur pasudan",
                                                "kotaID": "Jakarta Barat",
                                                "provinsiID": "Kemanggisan",
                                                "kodePos": "11480",
                                                "negara": "Indonesia",
                                                "parkir": "Yes",
                                                "pemakaian": "Indekos"
                                            }
                                        ],
                                        "operational_days": [
                                            {
                                                "days_name": "Monday",
                                                "from_time": "10:00PM",
                                                "to_time": "10:00PM",
                                                "all_day": 1
                                            },
                                            {
                                                "days_name": "Monday",
                                                "from_time": "10:00PM",
                                                "to_time": "10:00PM",
                                                "all_day": 1
                                            },
                                            {
                                                "days_name": "Tuesday",
                                                "from_time": "12:00PM",
                                                "to_time": "13:00PM",
                                                "all_day": 1
                                            },
                                            {
                                                "days_name": "Wednesday",
                                                "from_time": "10:00PM",
                                                "to_time": "10:00PM",
                                                "all_day": 1
                                            }
                                        ],
                                        "messenger": [
                                            {
                                                "pemakaian": "Utama",
                                                "namaMessenger": "(021) 3851185",
                                                "tipe": "Fax"
                                            },
                                            {
                                                "pemakaian": "Utama",
                                                "namaMessenger": "(021) 012345678",
                                                "tipe": "Office"
                                            }
                                        ],
                                        "email": [
                                            {
                                                "pemakaian": "Utama",
                                                "namaPengguna": "wahyudidanny23@gmail.com",
                                                "tipe": "Personal"
                                            },
                                            {
                                                "pemakaian": "Secondary",
                                                "namaPengguna": "wahyudidanny25@gmail.com",
                                                "tipe": "Personal"
                                            }
                                        ],
                                        "telepon": [
                                            {
                                                "pemakaian": "Utama",
                                                "nomorTelepon": "087888821648",
                                                "tipe": "Telepon Selular"
                                            },
                                            {
                                                "pemakaian": "Secondary",
                                                "nomorTelepon": "085265779499",
                                                "tipe": "Whatshapp"
                                            }
                                        ]
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Register Successfully",
                        "content": {
                            "application/json": {
                                "schema": {}
                            }
                        }
                    },
                    "200": {
                        "description": "Register Successfully",
                        "content": {
                            "application/json": {
                                "schema": {}
                            }
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "content": {
                            "application/json": {
                                "schema": {}
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request"
                    },
                    "404": {
                        "description": "Resource Not Found"
                    }
                },
                "security": [
                    {
                        "apiAuth": []
                    }
                ]
            },
            "delete": {
                "tags": [
                    "Location"
                ],
                "summary": "Delete Location",
                "description": "Delete Location , by delete location will update status isDeleted into 1)",
                "operationId": "delete location",
                "requestBody": {
                    "content": {
                        "multipart/form-data": {
                            "schema": {
                                "properties": {
                                    "id": {
                                        "type": "integer"
                                    }
                                },
                                "type": "object"
                            }
                        },
                        "application/json": {
                            "schema": {},
                            "examples": {
                                "Delete Location": {
                                    "summary": "Delete Location",
                                    "value": {
                                        "id": 1
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Delete location Successfully",
                        "content": {
                            "application/json": {
                                "schema": {}
                            }
                        }
                    },
                    "200": {
                        "description": "Delete location Successfully",
                        "content": {
                            "application/json": {
                                "schema": {}
                            }
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "content": {
                            "application/json": {
                                "schema": {}
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request"
                    },
                    "404": {
                        "description": "Resource Not Found"
                    }
                },
                "security": [
                    {
                        "apiAuth": []
                    }
                ]
            }
        },
        "/api/detaillocation": {
            "get": {
                "tags": [
                    "Location"
                ],
                "summary": "Get Location detail",
                "description": "get Location detail",
                "operationId": "detaillocation",
                "parameters": [
                    {
                        "name": "body",
                        "in": "path",
                        "required": true,
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "id": {
                                            "type": "text",
                                            "example": "1"
                                        }
                                    },
                                    "type": "object"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Get Data Location Detail Successfully",
                        "content": {
                            "application/json": {
                                "schema": {}
                            }
                        }
                    },
                    "200": {
                        "description": "Get Data Location Detail Successfully",
                        "content": {
                            "application/json": {
                                "schema": {}
                            }
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "content": {
                            "application/json": {
                                "schema": {}
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request"
                    },
                    "404": {
                        "description": "Resource Not Found"
                    }
                },
                "security": [
                    {
                        "apiAuth": []
                    }
                ]
            }
        },
        "/api/region": {
            "get": {
                "tags": [
                    "Location"
                ],
                "summary": "Get Region",
                "description": "Get Region",
                "operationId": "region",
                "parameters": [
                    {
                        "name": "body",
                        "in": "path",
                        "required": true,
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "provinsi": {
                                            "type": "text",
                                            "example": "ACEH"
                                        }
                                    },
                                    "type": "object"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Get Data Location Successfully",
                        "content": {
                            "application/json": {
                                "schema": {}
                            }
                        }
                    },
                    "200": {
                        "description": "Get Data Location Successfully",
                        "content": {
                            "application/json": {
                                "schema": {}
                            }
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "content": {
                            "application/json": {
                                "schema": {}
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request"
                    },
                    "404": {
                        "description": "Resource Not Found"
                    }
                },
                "security": [
                    {
                        "apiAuth": []
                    }
                ]
            }
        }
    },
    "components": {
        "securitySchemes": {
            "apiAuth": {
                "type": "http",
                "description": "Login with email and password to get the authentication token",
                "name": "Token based Based",
                "in": "header",
                "bearerFormat": "JWT",
                "scheme": "bearer"
            }
        }
    }
}